name: AWS Deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Use SSH key to access server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        script: |
          cd ~/csr-server2
          echo "PORT=3000"
          npm ci
          npm start -- --host=yigit-challenge-3-todo.co5qpleyensq.eu-north-1.rds.amazonaws.com /
                      --database=todo_app --password=test1234
          
   
