name: aws-deploy-server
on:
  push:
    branches:
      - main
env:
  AWS_REGION: ${{ secrets.REGION }}                
  REMOTE_HOST: ${{ secrets.HOST_DNS }}
  REMOTE_USER: ${{ secrets.USERNAME }}
  TARGET: ${{ secrets.TARGET_DIR }}

uses: uses: appleboy/ssh-action@v1.0.0
with:
  host: ${{ secrets.HOST_DNS }}
  username: ${{ secrets.USERNAME }}
  key: ${{ secrets.EC2_SSH_KEY }}
  script: |
    sudo apt-get -y update
    
                                                    
                                              
