name: AWS Deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: "eu-north-1"
      BUCKET_NAME: "lotec-challenge-3-yigit"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run build

      
    - name: Set up SSH key
      run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/todo-yigit.pem
          chmod 600 ~/.ssh/todo-yigit.pem
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
          find -type d -name 'csr-server2'
          
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SECRET_KEY }}
          HOST: ${{ secrets.HOST }}

  
    - name: Run remote command via SSH
      run: |
          ssh -i ~/.ssh/todo-yigit.pem ubuntu@${{ secrets.HOST }} 'sudo apt-get update' 
          ssh -i ~/.ssh/todo-yigit.pem ubuntu@${{ secrets.HOST }} 'sudo apt-get install nodejs -y'
          
    - name: Copy app.js file to Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_SECRET_KEY }}
        source: "./"
        target: "~/server"

    - name: Install and start PM2
      run: |
          ssh -i ~/.ssh/todo-yigit.pem ubuntu@${{ secrets.HOST }} 'sudo npm install -g pm2'
          ssh -i ~/.ssh/todo-yigit.pem ubuntu@${{ secrets.HOST }} 'pwd'
          ssh -i ~/.ssh/todo-yigit.pem ubuntu@${{ secrets.HOST }} 'pm2 start ~/servercsr-server2/dist/app.js'

