name: AWS Deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: "eu-north-1"
      BUCKET_NAME: "lotec-challenge-3-yigit"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
        
    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: 20
   
    
    - name: Use SSH key to access server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        script: |
          cd ~/csr-server2
          export PORT=3000
          export ORIGIN=*
          export REGION=eu-north-1
          export ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}
          export SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
          export BUCKET_NAME=lotec-challenge-3-yigit
          npm ci
          npm start -- --host=yigit-challenge-3-todo.co5qpleyensq.eu-north-1.rds.amazonaws.com --database=todo_app --password=${{ secrets.DB_PASSWORD}}
          
   
