name: AWS Deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: "eu-north-1"
      BUCKET_NAME: "lotec-challenge-3-yigit"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH key
      run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/todo-yigit.pem
          chmod 600 ~/.ssh/todo-yigit.pem
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
          whoami
          
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SECRET_KEY }}
          HOST: ${{ secrets.HOST }}

  
