name: AWS Deploy


on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: "eu-north-1"
      BUCKET_NAME: "lotec-challenge-3-yigit"
      
    strategy:
      matrix:
        node-version: [20.x]  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build with Esbuild
      run: |
        npx esbuild app.ts --platform=node --outfile=bundled.js
        pwd
        ls -a
