name: AWS Deploy

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: "eu-north-1"
      BUCKET_NAME: "lotec-challenge-3-yigit"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
          node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: | 
        npm run build
        pwd

      
    - name: Set up SSH key
      run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/todo-yigit.pem
          chmod 600 ~/.ssh/todo-yigit.pem
          ssh-keyscan $HOST >> ~/.ssh/known_hosts
          find -type d -name 'csr-server2'
          
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SECRET_KEY }}
          HOST: ${{ secrets.HOST }}

  
    - name: Run remote command via SSH
      run: |
          ssh -i ~/.ssh/todo-yigit.pem ubuntu@${{ secrets.HOST }} 'sudo apt-get update && sudo apt-get install nodejs -y'
          scp -r ./csr-server ubuntu@${{ secrets.HOST }}:~/
